"""phone_number mandatory

Revision ID: c7ac570c97ca
Revises: 17f24909794b
Create Date: 2025-05-15 11:32:24.284477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7ac570c97ca'
down_revision = '17f24909794b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###
